main: net.tfminecraft.thievery.Thievery
api-version: 1.20
name: Thievery
version: ${project.version}
author: Drefvelin

depend: [MMOCore, TLibs, RPCharacters]
softdepend: [OpenRP, AdvancedCrafting, InteractibleFurniture, DenarEconomy, GunsAndGadgets, Magic]
loadbefore: [OpenRP]

commands:
  thievery:
    useage: /<command>
    description: Thievery Command
  robbery:
    description: Robbery commands
  pickpocket:
    description: Pickpocket commands