main: net.tfminecraft.thievery.Thievery
api-version: '1.21.10'
name: Thievery
version: ${project.version}
author: Drefvelin

depend: [MMOCore, TLibs, RPCharacters]
softdepend: [AdvancedCrafting, InteractibleFurniture, DenarEconomy, GunsAndGadgets, Magic]

commands:
  thievery:
    useage: /<command>
    description: Thievery Command
  robbery:
    description: Robbery commands
  pickpocket:
    description: Pickpocket commands